services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: currency_quotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_READ_TIMEOUT=15s
      - SERVER_WRITE_TIMEOUT=15s
      - SERVER_IDLE_TIMEOUT=60s
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=currency_quotes
      - DB_SSLMODE=disable
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - EXTERNAL_API_URL=https://api.fxratesapi.com
      - EXTERNAL_API_TIMEOUT=10s
      - EXTERNAL_API_KEY=
      - WORKER_INTERVAL=30s
      - SHUTDOWN_TIMEOUT=30s
      - SUPPORTED_CURRENCIES=USD,EUR,MXN
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
